SchemaVersion: '1.0'
SageMaker:
  PythonSDK:
    Modules:
      RemoteFunction:
        # role arn is not required if in SageMaker Notebook instance or SageMaker Studio
        # Uncomment the following line and replace with the right execution role if in a local IDE
        RoleArn: arn:aws:iam::471094633457:role/SageMakerExecutionRole
        InstanceType: ml.m5.xlarge
        Dependencies: ./requirements.txt