#!/bin/bash

export SERVER="minecraft_server.$VANILLA_VERSION.jar"

if [ ! -e $SERVER ]; then
  echo "Downloading $SERVER ..."
  curl -sSL -o $SERVER $(curl -s $(curl -s 'https://launchermeta.mojang.com/mc/game/version_manifest.json' | jq --arg VANILLA_VERSION "$VANILLA_VERSION" --raw-output '[.versions[]|select(.id == $VANILLA_VERSION)][0].url') | jq --raw-output '.downloads.server.url')
fi

# Continue to Final Setup
exec /start-finalSetup01World $@
