version: 0.2

env:
  variables:
    INSTANCE_TYPE: "ml.m5.xlarge"

phases:
  pre_build:
    commands:
      - PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | grep -o "[0-9]\+")
      - echo "Running notebooks for PR $PR_NUM"

  build:
    commands:
      - run-pr-notebooks --pr $PR_NUM --instance $INSTANCE_TYPE
