channels:
   - conda-forge

dependencies:
   - IPython==7.6.1
   - sphinx==4.2.0
   - Jinja2==3.0.2
   - pip
   - pip:
      - nbsphinx==0.8.7
      - prompt-toolkit==2.0.10
      - sagemaker
      - sphinx-rtd-theme==1.0.0
