JOB_TYPE:                             "TRAINING"
WORLD_NAME:                           ""
SAGEMAKER_SHARED_S3_BUCKET:           ""
SAGEMAKER_SHARED_S3_PREFIX:           ""
TRAINING_JOB_ARN:                     ""
METRICS_S3_BUCKET:                    ""
METRICS_S3_OBJECT_KEY:                "/training_metrics.json"
SIMTRACE_S3_BUCKET:                   ""
SIMTRACE_S3_PREFIX:                   "/iteration-data/training"
AWS_REGION:                           ""
TARGET_REWARD_SCORE:                  "None"
NUMBER_OF_EPISODES:                   "0"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID:  ""
CHANGE_START_POSITION:                "true"
ALTERNATE_DRIVING_DIRECTION:          "false"
REVERSE_DIR:                          "false"
KINESIS_VIDEO_STREAM_NAME:            ""
REWARD_FILE_S3_KEY:                   ""
MODEL_METADATA_FILE_S3_KEY:           ""
NUMBER_OF_RESETS:                     "0"
CAR_COLOR:                            "Blue"
ENABLE_DOMAIN_RANDOMIZATION:          "false"
NUM_WORKERS:                          "1"

# Modify this for obstacle avoidance (Having NUMBER_OF_OBSTACLES = 0 nullifies all these parameters)
NUMBER_OF_OBSTACLES:                  "0"
MIN_DISTANCE_BETWEEN_OBSTACLES:       "2.0"
RANDOMIZE_OBSTACLE_LOCATIONS:         "false"
IS_OBSTACLE_BOT_CAR:                  "false"

# Modify this for Head to bot (Having NUMBER_OF_BOT_CARS = 0 nullifies all these parameters)
NUMBER_OF_BOT_CARS:                   "0"
IS_LANE_CHANGE:                       "false"
LOWER_LANE_CHANGE_TIME:               "3.0"
UPPER_LANE_CHANGE_TIME:               "5.0"
LANE_CHANGE_DISTANCE:                 "1.0"
MIN_DISTANCE_BETWEEN_BOT_CARS:        "2.0"
RANDOMIZE_BOT_CAR_LOCATIONS:          "true"
BOT_CAR_SPEED:                        "0.2"

# Only for the mp4 videos
MP4_S3_BUCKET:                        ""
MP4_S3_OBJECT_PREFIX:                 "/iteration-data/training"
RACE_TYPE:                            "TIME_TRIAL"
VIDEO_JOB_TYPE:                       "RACING"
DISPLAY_NAME:                         "LongLongRacerNameBlaBlaBla"
RACER_NAME:                           "racer-alias"
MODEL_NAME:                           "bla-bla-model-user-created-in-customer"
LEADERBOARD_TYPE:                     "LEAGUE"
LEADERBOARD_NAME:                     "2020 MARCH QUALIFIER"
