# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AmazonAIAlgorithmsIO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AmazonAIAlgorithmsIO.proto',
  package='AmazonAIAlgorithmsIO',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x41mazonAIAlgorithmsIO.proto\x12\x14\x41mazonAIAlgorithmsIO\"\\\n\x06Record\x12\x10\n\x04keys\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x12\n\x06values\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\r\n\x05label\x18\x03 \x01(\x01\x12\x0b\n\x03uid\x18\x04 \x01(\t\x12\x10\n\x08metadata\x18\x05 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='AmazonAIAlgorithmsIO.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='AmazonAIAlgorithmsIO.Record.keys', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='values', full_name='AmazonAIAlgorithmsIO.Record.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='label', full_name='AmazonAIAlgorithmsIO.Record.label', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='AmazonAIAlgorithmsIO.Record.uid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='AmazonAIAlgorithmsIO.Record.metadata', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['Record'] = _RECORD

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(
  DESCRIPTOR = _RECORD,
  __module__ = 'AmazonAIAlgorithmsIO_pb2'
  # @@protoc_insertion_point(class_scope:AmazonAIAlgorithmsIO.Record)
  ))
_sym_db.RegisterMessage(Record)


_RECORD.fields_by_name['keys'].has_options = True
_RECORD.fields_by_name['keys']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_RECORD.fields_by_name['values'].has_options = True
_RECORD.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
