backend: "fil"
max_batch_size: 882352
input [                                 
 {  
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 15 ]                    
  } 
]
output [
 {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [{ kind: KIND_GPU }]
parameters [
  {
    key: "model_type"
    value: { string_value: "xgboost_json" }
  },
  {
    key: "predict_proba"
    value: { string_value: "false" }
  },
  {
    key: "output_class"
    value: { string_value: "true" }
  },
  {
    key: "threshold"
    value: { string_value: "0.5" }
  },
  {
    key: "storage_type"
    value: { string_value: "AUTO" }
  }
]

dynamic_batching {}