ARG REGISTRY_URI
FROM ${REGISTRY_URI}

RUN pip install -U pip
RUN pip install -U wheel setuptools
RUN pip install --no-cache-dir autogluon==0.1.0

RUN pip install PrettyTable

# Defines inference.py as script entrypoint
ENV SAGEMAKER_PROGRAM inference.py
