name: "ensemble"
platform: "ensemble"
max_batch_size: 16
input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "finaloutput"
    data_type: TYPE_FP32
    dims: [384]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "INPUT0"
      }
      output_map {
        key: "OUTPUT0"
        value: "token_ids"
      }
      output_map {
        key: "OUTPUT1"
        value: "attn_mask"
      }
    },
    {
      model_name: "bert-trt"
      model_version: -1
      input_map {
        key: "token_ids"
        value: "token_ids"
      }
      input_map {
        key: "attn_mask"
        value: "attn_mask"
      }
      output_map {
        key: "output"
        value: "output"
      }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map {
        key: "TOKEN_EMBEDS_POST"
        value: "output"
      }
      input_map {
        key: "ATTENTION_POST"
        value: "attn_mask"
      }
      output_map {
        key: "SENT_EMBED"
        value: "finaloutput"
      }

    }
  ]
}