FROM ghcr.io/allenai/pytorch:1.13.1-cuda11.7-python3.10-v1.2.2

RUN apt update
RUN apt install wget git -y
RUN apt install libgl1-mesa-glx -y
RUN pip install opencv-python-headless

RUN mkdir -p /opt/ml/code
COPY serve /opt/ml/code
COPY stable-diffusion-webui /opt/ml/code/
RUN git clone https://github.com/Mikubill/sd-webui-controlnet.git /opt/ml/code/extensions/sd-webui-controlnet

RUN apt install build-essential

RUN mkdir -p /root/.cache/huggingface/accelerate
COPY default_config.yaml /root/.cache/huggingface/accelerate/

RUN pip install boto3 huggingface_hub ninja triton deepspeed accelerate
RUN conda install xformers -c xformers -y

WORKDIR /opt/ml/code