FROM ghcr.io/allenai/pytorch:1.13.1-cuda11.7-python3.10-v1.2.2

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install --assume-yes apt-utils -y

RUN apt update
RUN apt install wget git -y
RUN apt install libgl1-mesa-glx -y
RUN apt install build-essential
RUN pip install opencv-python-headless
RUN pip install sagemaker-training
RUN pip install triton
RUN conda install xformers -c xformers -y

RUN mkdir -p /opt/ml/code

ADD https://api.github.com/repos/xieyongliang/stable-diffusion-webui/git/refs/heads/api webui.version.json
RUN git clone https://github.com/xieyongliang/stable-diffusion-webui.git /opt/ml/code -b api

ADD https://api.github.com/repos/xieyongliang/sd_dreambooth_extension/git/refs/heads/main dreambooth.version.json
RUN git clone https://github.com/xieyongliang/sd_dreambooth_extension.git /opt/ml/code/extensions/sd_dreambooth_extension

COPY train.py /opt/ml/code/

ENV SAGEMAKER_PROGRAM train.py

ENTRYPOINT []
