backend: "python"
max_batch_size: 0
model_transaction_policy {
    decoupled: true
}

input [ 
    {
        name: "text_input"
        data_type: TYPE_STRING
        dims: [1]
    },
    {
        name: "sampling_parameters"
        data_type: TYPE_STRING
        dims: [1]
        optional: true
    }
] 
output [
    {
    name: "text_output"
    data_type: TYPE_STRING
    dims: [-1]
    }
]

instance_group [
    {
    count: 1
    kind: KIND_MODEL
    }
]
